### PR TITLE
Added ~ascii command

### PR DESCRIPTION
**Pull request by mrb25**
~ascii *text* -- returns the input text as ascii art

### CODE REVIEW

**Comment by mrb25** [comment]
Also added Issue #30 fix. Reddit commands now pull text from self posts or links from others.

**Comment by JessWalters** [comment]
Can you remove the .pyc files? And change the client id back? I will probably put that in the config too later. This looks really good though 👍

**Comment by mrb25** [comment]
Fixed requested @JessWalters

**Comment by JessWalters** [comment]
+1 from me, Thanks

**Pull request merged**
