### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kjkeith**
FTFY

### CODE REVIEW

**Comment by demisardonic** [comment]
This is an urgent fix.

**Comment by demisardonic** [comment]
Hey can we get this taken care of quick

**Comment by demisardonic** [comment]
like really quick

**Comment by demisardonic** [comment]
People have begun complaining

**Comment by demisardonic** [comment]
It looks like it failed integration tests, but everything seems alright

**Comment by demisardonic** [comment]
Is Vinny no longer being developed?

**Comment by demisardonic** [comment]
This change really needs to go through

**Comment by JessWalters** [comment]
+1

**Comment by demisardonic** [comment]
I agree with your decision to reopen this pull request

**Comment by kjkeith** [comment]
I agree. I believe it was the best for Vinny.

**Comment by bdog73** [comment]
Good reopen choice. Fix needed immediately. Potentially broken. Please finish, thanks.

**Comment by theluke7** [comment]
About damn time

**Pull request merged**
